### ISSUE TITLE
[Epic] Plan for week of 8/25 – 8/31

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#113]
### PM

- [ ] OneApp Change Requests - New Data Fields (Gender, Crowdfunding, etc.) #16
- [x] Figure out who can work on URL structure and SEO #56
- [x] Investigate making GitHub repo public #87

### Design

- [ ] Epic: Section 1 — Basic Information #72
- [ ] Migrate designs to a clean design system/file #116
- [x] User testing (ongoing)

### Frontend

Build login screens #23

- [ ] Account sign up #24
- [ ] Account sign in #25
- [ ] Forgot username #26
- [ ] Forgot password #27
- [ ] Check application status #28
- [ ] View application list #29
 
Other to-dos:

- [x] Research and development of GraphQL client-side interface #119
- [ ] Review homepage, login screens, style guide with Melissa #120

### Backend

- [x] Build out the OneApp GraphQL server foundation #11
- [x] Make OneApp repo public #115
- [ ] Setup USDS staging environment #48
- [ ] Setup training plan for NJ OneApp developers #64
- [ ] Work on GraphQL - Add login data; Build in security support to rate limit certain data #121
