### ISSUE TITLE
[BE] Work on GraphQL - Add login data; Build in security support to rate limit certain data

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#121]
## Background

Ron mentioned in 8.27.20 planning that he completed adding login data and some work on rate limiting data in GraphQL. This ticket is to track that work.

## Tasks

- [x] Add login data
- [x] Build in security support to rate limit login data
- [ ] Forgot password / username
- [x] Better error handling (errors should not fall back on unauthorized)

**Comment by ronaldheft-usds** [comment]
Been on hold as working toward #48

**Comment by leahbannon2** [comment]
Need to discuss more with @mikepif since this affects:
- translation
- sending email

**Comment by ronaldheft-usds** [comment]
Talked through this in #129. Created tickets that will need to be done as part of this task.

**Comment by Samara-Strauss** [comment]
Ron to clean up/merge code, likely by EOD.

**Comment by ronaldheft-usds** [comment]
Merged!
