### ISSUE TITLE
[PM] Document MVP requirements

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#122]
## Background

We need to clearly define what is part of the MVP for this project and make sure the NJ team and our team are in clear agreement.

To the best of our knowledge, the following is included in the MVP:

- Login pages (login, password validation, forgot password? reset)
- Save for later functionality (come back later to complete the app)
- Full benefit application, which includes
- All 8 sections of the application
- Full Spanish translation
- Handoff of new form (markup or form builder?)
- The build being fully responsive
- The build meeting all required accessibility guidelines

It is unclear whether the build includes the following:

- Caseworker-specific functionality

## Tasks

- [x] Determine whether the above list is accurate and if anything is missing
- [x] Determine client vs worker view requirements #2
- [ ] Create documentation
- [ ] Review with our team
- [ ] Review with NJ team for final approval/consensus

**Comment by leahbannon2** [comment]
- Login pages (login, password validation, forgot password? reset)
- Save for later functionality (come back later to complete the app)
- Full benefit application, which includes
  - All 8 sections of the application
  - Full Spanish translation (NJ is managing translation, USDS is including in MVP)
- Handoff of new form (markup or form builder?)
- The build being fully responsive
- The build meeting all required accessibility guidelines
- Caseworker differences 
- Necessary changes based on new or existing laws and regulations

**Comment by Samara-Strauss** [comment]
Is this the full list of requirements?

**Comment by leahbannon2** [comment]
I need to validate with the team and the master spreadsheet. Will review with NJ at 9/9 design meeting.

**Comment by Samara-Strauss** [comment]
- Blocked. This is mostly done, but we need to determine at what level we are re-architecting this application, and that can only be determined after Melissa completes her IA work and we're able to review that with NJ team. Moving to backlog until we are able to move this forward.

**Comment by leahbannon2** [comment]
We've settled on quick submit for MVP: #262
