### ISSUE TITLE
[Epic] Plan for week of 9/1 - 9/7

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#123]
### PM

- [ ] OneApp Change Requests - New Data Fields (Gender, Crowdfunding, etc.) #16
- [ ] Figure out process for NJ team providing Spanish translation #58
- [x] Determine client vs worker view requirements #2
- [ ] Document MVP requirements #122
- [x] Get Zenhub back up and running once repo has been made public #126
- [ ] Determine who will conduct QA and accessibility reviews #47
- [ ] Move notes to wiki #103

### Design

Finish Section 1: Basic info design #72 

- [ ] Review policy documentation from NJ team #73
- [ ] Make updates to the basic information section based on policy requirements and other NJ feedback #74
- [ ] Document validation rules & copy #75
- [ ] Document any conditional functionality #76
- [ ] Provide content for dropdowns #77

Other tasks

- [ ] Go through client feedback for homepage and login screens and make updates #132
- [x] Figure out if there are additional sections of OneApp that we need to design #124
- [ ] Migrate designs to a clean design system/file #116
- [ ] User testing (Ongoing)

*Content*

- [ ] Week of 9/1: Review content feedback from NJ #117
- [ ] Figure out regular content sync cadence/process #118
- [ ] Design to send finished Section 1: Basic info design to content for review #128

### Frontend

- [ ] Run lighthouse tool against existing site to generate a list of SEO suggestions #125
- [x] Account sign up #24
- [x] Account sign in #25
- [ ] Forgot username #26
- [ ] Forgot password #27
- [ ]  GraphQL: What are the most important pieces of data on the frontend? What would be a blocker? #129
- [x] Talk to Ron about where to store Spanish translation for the app #131

### Backend

- [ ] GraphQL: What are the most important pieces of data on the frontend? What would be a blocker? #129
- [x] Create audit of Oracle procedures #55
- [ ] Setup USDS staging environment #48
- [x] Make sure the contract for Treehouse goes through #64 
- [ ] Work on GraphQL - Add login data; Build in security support to rate limit certain data #121

**Comment by Samara-Strauss** [comment]
Move to next week

Document mapping between old application and new application #78
Review SEO/URL/Redirect plan with Danielle #114
Review Section 2: Income designs with NJ client team #127
