### ISSUE TITLE
[Design] Figure out if there are additional sections of OneApp that we need to design

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#124]
## Background

In Jenn's current mockups, it is suggested that there are 8 sections of the application. However, only 6 sections are shown in InVision. We need to figure out if there are sections of the app Jenn didn't get to when she was working on the design, and, if so, what work remains.

## Tasks

- [x] Regroup with Jenn
- [ ] Determine what work is outstanding
- [ ] (If necessary) Regroup with the NJ client team with any questions

**Comment by melissajschaff** [comment]
Updated Invision v3 screens with correct number of sections and progress bar. 

There will be 6 sections:
1. Basic information
2. Income
3. Resources
4. Expenses
5. Final steps
6. Review & submit

**Comment by Samara-Strauss** [comment]
Great! Anything else here, or can we close this out?

**Comment by Samara-Strauss** [comment]
Closing. I think any further changes that come out of this will be a result of the IA mapping work Melissa is doing.
