### ISSUE TITLE
[FE] SEO: Run lighthouse tool against existing site to generate a list of SEO suggestions

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#125]
## Background

Mike mentioned in our 8.27.20 planning session that he was going to run the lighthouse tool against the existing site to generate a list of SEO suggestions. This ticket is to track that work.

## Tasks

- [x] Run lighthouse tool
- [x] Generate list of SEO suggestions
- [ ] Share with the team

**Comment by Samara-Strauss** [comment]
Mike PROMISES this week that he will get this ticket done. **PROMISES**
