### ISSUE TITLE
[Design] Go through client feedback for homepage and login screens and make updates

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#132]
## Background

In our 9.1.20 planning session, Melissa mentioned she received feedback from the NJ client team on the homepage and login pages for OneApp. She needs to go through that feedback and handoff updates to Mike as necessary.

## Tasks

- [ ] Review client feedback
- [ ] Make design updates
- [ ] Handoff updates to Mike

**Comment by Samara-Strauss** [comment]
On hold until Melissa gets back. I moved this to the backlog.

**Comment by leahbannon2** [comment]
Allyce has taken the lead on this and created new issues to reflect the work.
