### ISSUE TITLE
Initial meeting: Organize strategy to better understand OneTrac, FAMIS, and UAP and the external calls they make (e.g. to SSA)

### ISSUE THREAD

**Issue by leahbannon2** [newjersey/dhs-oneapp#134]
This would help
- longterm strategy to better understand how these systems interact with other federal systems
- better understanding caseworker flow and finding potential problems with our MVP approach

I think we need to 
- [x] start a new system diagram that we can collaborate on as a team
- [x] review with Carmen and figure out who to speak with?
- [x] Have initial discussion with folks who manage and know these systems and the external calls they make (follow-up discussions will be captured in a separate ticket)

## Tasks 

- [x] Ron to set up meeting with Tom
- [x] Leah, Ron, Mike to have initial meeting with Tom

Additional follow-up and tickets will come out of this

**Comment by Samara-Strauss** [comment]
Next steps on this: Ron to set up a call with Tom to discuss downstream systems re: integration testing

**Comment by Samara-Strauss** [comment]
- Ron needs to reach out to Tom this week

**Comment by leahbannon2** [comment]
No response from Tom yet and we missed him in the Monday meeting, so I'm reaching out to Carmen to discuss setting up a regular sync with her and Tom so we can discuss this and other questions that keep come up, like transition.

**Comment by leahbannon2** [comment]
No response from Tom still, so I'm reaching out to Carmen to set up an ongoing meeting time w/ her and Tom.

Update: Carmen said to ask Tom, so I emailed them both.

**Comment by leahbannon2** [comment]
We heard back from Tom about folks to meet with, I've started reaching out to coordinate times to meet.

**Comment by Samara-Strauss** [comment]
Meeting is rescheduled for week of 10/6
