### ISSUE TITLE
[Epic] Plan for week of 9/8 - 9/14

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#142]
### PM (Leah)

- [ ] Determine who will conduct QA and accessibility reviews #47
- [ ] Resolve some of the existing InVision comments with NJ team #153
 - [ ] Determine how to help Melissa move forward IA spreadsheet during RI sprint #154

### Design (Melissa)

- [ ] IA mapping: Complete work for Section 1: Basic info #144

### Frontend (Mike)

- [ ] SEO: Run lighthouse tool against existing site to generate a list of SEO suggestions #125
- [x] Forgot username #26
- [x] Forgot password #27
- [ ] GraphQL: What are the most important pieces of data on the frontend? #129
- [ ] IA mapping: Generate a list of old questions to fields in the database #148
- [x] Setup training plan for NJ OneApp developers: Assemble a list of frontend courses #64

### Backend (Ron)

- [ ] GraphQL: What are the most important pieces of data on the frontend? #129
- [ ] (Stretch goal) Work on GraphQL - Add login data; Build in security support to rate limit certain data #121
- [x] Spanish translation: How should we handle emails and other details? #157
- [ ] Understanding downstream systems: Set up meeting with Tom #134

Currently blocked: Setup USDS staging environment #48

### Planning/ticketing (Samara)

- [x] Create tickets for design review for #24 and #25
- [x] Create epic and issues for IA mapping Melissa and Mike are doing
- [x] Check in with Ron once he's back to determine what happened last week and what he has time for this week
