### ISSUE TITLE
[Epic] Design: IA mapping for OneApp

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#143]
## Background

Melissa has undertaken the huge task of mapping the existing IA of OneApp, the new structure we are proposing, and how these two versions map to each other. This epic is to track to-dos related to the IA mapping that is happening.

### Mapping

- [ ] Complete mappings for Section 1: Basic Info
- [ ] Complete mappings for Section 2: Income
- [ ] Complete mappings for Section 3: Resources
- [ ] Complete mappings for Section 4: Expenses
- [ ] [FE] Generate a list of old questions to fields in the database

### Client reviews/approval

- [ ] Review Section 1: Basic Info
- [ ] Review Section 2: Income
- [ ] Review Section 3: Resources
- [ ] Review Section 4: Expenses

## Acceptance criteria

- [ ] Documentation is complete
- [ ] NJ has reviewed and approved structure for new sections

**Comment by allyceh** [comment]
@leahbannon2 @bestes-usds @melissajschaff and I met so that Melissa could walk us through the spreadsheet. Here are some ideas that came up during the conversation: 

- Provide NJ with a spreadsheet (or word doc, or something) that shows them:
  - The questions that are asked in the new prototype and the current questions they map to
  - Possible responses for drop downs or radio buttons
- InVision can be difficult to use for design reviews. Consider exporting PDFs of screens rather than using the InVision prototype.

**Comment by allyceh** [comment]
Next steps: 

- Once @melissajschaff gets back from PTO, sync on finishing the spreadsheet and understand when @allyceh and @bestes-usds can help. This will likely be after quick submit work is finished. 
- Determine if everything from OneApp made it in to the prototype. 
- Consider piloting a spreadsheet and design PDF review with NJ for quick submit. Understand if reviewing questions in a spreadsheet is helpful for them prior to looking at screens. 
- Internally, conduct an audit of the questions in the current OneApp. Determine if we can propose the removal of questions to make the application more concise and document application questions that we need to understand more about from NJ.
