### ISSUE TITLE
[Design] Review & finalize IA mapping for Section 3: Resources

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#151]
## Background 

Epic #143

Melissa has undertaken the huge task of mapping the existing IA of OneApp, the new structure we are proposing, and how these two versions map to each other. This ticket is for tracking the review and approval process for Section 3: Resources with the NJ team.

Note: May break this down into more tickets if the review process ends up being complex.

## Tasks

- [ ] Review IA mapping of old sections --> new Section 3: Resources with NJ team.
- [ ] Make updates based on NJ feedback.
- [ ] Final review with NJ.

## Acceptance criteria

- [ ] NJ has approved the IA for Section 3: Resources.
