### ISSUE TITLE
[PM] IA mapping: Determine how to help Melissa move forward IA spreadsheet during RI sprint

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#154]
## Background

Epic #143

Melissa has undertaken the huge task of mapping the existing IA of OneApp, the new structure we are proposing, and how these two versions map to each other. 

As part of this, Leah is going to try to figure out in what ways she can help Melissa to move forward the IA work while Melissa is working on the RI sprint. This issue is for tracking that planning and documenting next steps for Leah.

## Tasks

- [x] Determine in what ways, if any, Leah can help Melissa with moving the IA work forward while Melissa is out on the RI sprint
- [x] Document those next steps here
- [ ] (If applicable) Create any necessary follow-up tickets

**Comment by Samara-Strauss** [comment]
Leah and Melissa to meet this week to discuss.

**Comment by leahbannon2** [comment]
After discussing with Melissa and USDS leadership, I decided to put this work on hold last week. I emailed NJ to let them know that we will be pausing design and focusing on engineering work for the next few weeks while Melissa is out. 

I'm keeping this open while I'm still trying to find time to meet with Melissa so I can help with some of the legwork on this.

**Comment by Samara-Strauss** [comment]
Thanks for the update! Sounds like we can close out this ticket and pursue additional work when Melissa is back.
