### ISSUE TITLE
[PM] OneApp Change Requests - New Data Fields (Gender, Crowdfunding, etc.)

### ISSUE THREAD

**Issue by johnhashva** [newjersey/dhs-oneapp#16]
## Background

**Is your UX/Design request related to a problem? Please describe.**

NJ DHS has outlined a number of request changes to the OneApp flow, including the addition of new data fields (e.g. Gender, Crowdsourcing) and positional changes for some sections of the application.

**Possible work requests**
- [work request from 9/2019](https://github.com/usds/covid-19/blob/master/new-jersey/safety-net-benefits/dhs/Final%20OneApp%20Lang.%20Work%20Request%20(002).pdf)
- [gender identity updates](https://github.com/usds/covid-19/blob/master/new-jersey/safety-net-benefits/dhs/Work%20Request%20-%20FAMIS-UAP%20Gender%20Identity%20Updates.pdf)
- ["OneApp updates"](https://github.com/usds/covid-19/blob/master/new-jersey/safety-net-benefits/dhs/Work%20Request%20-%20OneApp%20Updates(Signed).pdf)
- [institutional applicants](https://github.com/usds/covid-19/blob/master/new-jersey/safety-net-benefits/dhs/Work%20Request--Institutional%20Applicants-OneApp.pdf)
- [download a spreadsheet with some (all?) changes](https://app.zenhub.com/files/284097858/3445116e-16f7-4685-9058-df1908dc9528/download)

## Tasks

- [ ] Leah to review the spreadsheet in this ticket
- [ ] Review with NJ team and get answers to outstanding questions
- [ ] Once all questions are answered, work with Samara to get tickets created for design/dev

**Comment by leahbannon2** [comment]
Gender question approach we'll discuss in design review tomorrow, considering a few values: 
- Collecting less data on vulnerable populations is good
- Specifying why data is being collected

This is the rough approach we'll propose. Still need content review:
2 gender questions
1 - What is the gender on your government issued ID (required for identity check)
answers: female, male
2 - What is your gender identity, if different from above (optional)
answers: female, male, non-binary

**Comment by Samara-Strauss** [comment]
To do — Leah will create the following issues:

- [ ] Gender question
- [ ] Define additional changes and assign to Melissa

**Comment by Samara-Strauss** [comment]
- Blocked until we can figure out what the upstream systems are connecting to and checking to validate this question.
  - Next steps: Ron will figure out who to talk to about this. #134 
- Blocked until the IA spreadsheet Melissa is working on is able to support changes requested by the NJ team.
