### ISSUE TITLE
[Epic] Plan for week of 9/15 - 9/21

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#175]
### PM (Leah)

- [x] Determine how to help Melissa move forward IA spreadsheet during RI sprint #154
- [ ] Move notes to wiki #103
- [ ]  Follow-up with Tom on developer training courses #178
- [ ] Initial meeting: Organize strategy to better understand OneTrac, FAMIS, and UAP and the external calls they make (e.g. to SSA) #134

### Design (Melissa)

On hold this week: RI sprint

### Frontend (Mike)

- [ ] SEO: Run lighthouse tool against existing site to generate a list of SEO suggestions #125
- [x] [FE/BE] GraphQL: What are the most important pieces of data on the frontend? #129
- [x] An API end-point for getting and updating the form configuration #174
- [ ] Form builder updates and related components for Basic Information section #176

Check in on #101 in planning

### Backend (Ron)

- [x]  Setup training plan for NJ OneApp developers #64
- [ ] Work on GraphQL - Add login data; Build in security support to rate limit certain data #121
- [ ] Initial meeting: Organize strategy to better understand OneTrac, FAMIS, and UAP and the external calls they make (e.g. to SSA) #134
- [x] Setup USDS staging environment #48

### Samara

- [x] Create review tickets for forgot username and forgot password screens (added to ticket 120)
- [x] Create new ticket for Add saving & loading of form config (from temporary api) (separating #176)

**Comment by Samara-Strauss** [comment]
For future sprints:

9/22 

- [BE] IA mapping: Generate a list of old questions to fields in the database #148
- [FE] Add session support #177
