### ISSUE TITLE
[PM] Follow-up with Tom on developer training courses

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#178]
## Background

In our 9.15.20 planning, we discussed that we need to be following up and checking in with the NJ team to make sure they are making progress on their Treehouse developer courses. Leah plans to do this by having Tom from NJ join the team's Monday meeting and reviewing the training course list with him.

## Tasks

- [x] Get training course list from Mike/Ron
- [x] Invite Tom to Monday meetings
- [x] Meet with Tom to review training course list

**Comment by Samara-Strauss** [comment]
Still haven't heard back from Tom. Will move forward once Leah can get in touch with him.

**Comment by leahbannon2** [comment]
I've sorted out a strategy for this - reached out to Tom about meeting with him and Giuseppe next Tuesday.

**Comment by Samara-Strauss** [comment]
Meet scheduled for 10/6
