### ISSUE TITLE
[Epic] Plan for week of 9/22 - 9/28

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#188]
### PM (Leah)

- [ ] Move notes to wiki #103
- [ ] Follow-up with Tom on developer training courses #178
- [ ]  Initial meeting: Organize strategy to better understand OneTrac, FAMIS, and UAP and the external calls they make (e.g. to SSA) #134
- [ ] BEGIN: Prepare caseworker interview questions and testing #135

Also worked on:

- #202

### Design (Melissa)

On hold this week: RI sprint

### Frontend (Mike)

- [x] SEO: Run lighthouse tool against existing site to generate a list of SEO suggestions #125
- [ ] Form builder updates and related components for Basic Information section #176
- [ ] As a user, I need to be able to pick a username that isn't already taken #101
- [ ] Help Ron as needed with #148 

### Backend (Ron)

- [ ] (Maybe, pending help from Lisa C) Migrate staging environment to USDS's cloud.gov account #181
- [x] Work on GraphQL - Add login data; Build in security support to rate limit certain data #121
- [ ] Endpoint for resetting a password after a user confirms their hint question #189
- [x] [BE] IA mapping: Generate a list of old questions to fields in the database #148

Also worked on mentoring/training discussions (#178)

### Samara

- [x] Samara created tickets: #189, #190, #191, #192, #193, #194

**Comment by Samara-Strauss** [comment]
For next week

- [ ] Back-end will return standard error messages for all errors, include translation codes. (#186)
- [ ] Back-end will provide endpoint for returning all translation values; front-end to leverage this endpoint to look up translation messages. (#173)
- [ ] Front-end to send locale code to all back-end endpoints via header. Will be used by back-end for translation endpoint and any stored procedures that require locale code. (#185)
