### ISSUE TITLE
[PM/Design] Determine client vs case worker view requirements

### ISSUE THREAD

**Issue by johnhashva** [newjersey/dhs-oneapp#2]
## Background

One big outstanding question for this project is whether there will be any differences between the client/caseworker views for the application. We need to determine:

- What does NJ think we are delivering them? Are there client/caseworker permissions they are expecting us to deliver? Are there client/caseworker permissions that are required?
- If NJ is expecting a difference in the client/caseworker permissions/flows, what are they?

## Tasks

- [x] Determine a plan for how to approach NJ about client and caseworker view requirements/permissions.
- [x] Meet with NJ to discuss client/caseworker view requirements/permissions.
- [ ] Document decisions from that discussion.
- [ ] Create design tickets for any new functionality we plan to implement.

**Comment by leahbannon2** [comment]
New Jersey indicated they want the caseworker flow to be the same as the new flow we're creating. We're aware of a few small differences that need to be in place from the code differences. I'm going to close this issue and open a new one for Mike or Ron to list the differences #133

**Comment by Samara-Strauss** [comment]
Closing — #133, #134, and #135 are follow-ups.
