### ISSUE TITLE
 [Epic] Plan for week of 9/29 - 10/5

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#203]
### PM (Leah)

- [x] Move notes to wiki #103
- [x] Follow-up with Tom on developer training courses #178
- [ ] Initial meeting: Organize strategy to better understand OneTrac, FAMIS, and UAP and the external calls they make (e.g. to SSA) #134
- [ ] Prepare caseworker interview questions and testing #135
- [ ] Schedule and hold meeting with NJ and NAVA #202
- [x] Grant NJ DHS team access to NJ GitHub #208

### Design (Melissa)

On hold this week: RI sprint

### Frontend (Mike)

- [ ] Form builder updates and related components for Basic Information section #176
- [ ] As a user, I need to be able to pick a username that isn't already taken #101
- [ ] Upgrade to VueJS #204

### Backend (Ron)

- [x] Migrate staging environment to USDS's cloud.gov account #181
- [ ] Create endpoint for resetting a password after a user confirms their hint question #189
- [x] Back-end will return standard error messages for all errors, include translation codes #186
- [x] Back-end will provide endpoint for returning all translation values; front-end to leverage this endpoint to look up translation messages #173
- [x] Back-end and front-end passes a standard language header code #185

### Samara
