### ISSUE TITLE
[Epic] Translation of OneApp Application into Spanish

### ISSUE THREAD

**Issue by johnhashva** [newjersey/dhs-oneapp#21]
## Background

It is a legal requirement that we enable/support Spanish translation. The following needs to happen for that to be complete:

## PM

- [ ] Figure out process for NJ team providing Spanish translation #58

## Design

- [ ] Confirm when all copy is complete

## Frontend

- [ ] Export all copy and send to NJ team for Spanish translation #59

Implement Spanish translation on all sections of on OneApp:

- [ ] Homepage #60
- [ ] OneApp steps / process overview #61
- [ ] Section 0: Account and application screens #62
- [ ] Section 1: Basic Information #63

(Will add other sections as those are confirmed)
