### ISSUE TITLE
FE/BE: Form submission integration testing

### ISSUE THREAD

**Issue by mikepif** [newjersey/dhs-oneapp#222]
Investigate automated testing setup for form quick submit;

- [ ] Research best practice
- [ ] Build out form component unit tests
- [ ] Build out form submission unit test
- [ ] Create test case
- [ ] Run test case against existing OneApp application and create snapshot of database values
- [ ] Create script to compare database values against test case expected values
