### ISSUE TITLE
[Epic] Plan for week of 10/6 - 10/12

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#223]
### PM (Leah)

- [x] Initial meeting: Organize strategy to better understand OneTrac, FAMIS, and UAP and the external calls they make (e.g. to SSA) #134
- [ ] Schedule and hold meeting with NJ and NAVA #202
- [x] Onboarding Allyce #227
- [x] sprint planning prep #228

**Leah may add additional to-dos.**

### Design (Melissa)

TBD

### Content (Allyce)

- [x] Onboarding: Reviewing background documentation (**Needs ticket**)
- [x] Sync with Melissa and Brian Estes (**Needs ticket**)

**Allyce may add additional tickets after sync with Melissa and Brian.**

### Frontend (Mike)

- [ ] Form builder updates and related components for Basic Information section #176
- [ ] As a user, I need to be able to pick a username that isn't already taken #101
- [ ] add yellow banner warning staging is staging #218
- [ ] Build out form component unit tests (**Needs ticket**)
- [ ] (Stretch goal) #193

### Backend (Ron)

- [ ] Create endpoint for resetting a password after a user confirms their hint question #189
- [ ] Document Windows installation directions for NJ DHS team #207
- [ ] Backend planning for Quick Submit #226
