### ISSUE TITLE
[Epic] Frontend: Section 0 — Account and application screens

### ISSUE THREAD

**Issue by melissajschaff** [newjersey/dhs-oneapp#23]
## Background

This epic is for all of the login-related screens

### Initial build

- [x] Account sign up #24
- [x] Account sign in #25
- [x] Forgot username #26
- [x] Forgot password #27
- [ ] Check application status #28
- [ ] View application list #29

### Design validation

Adding these tickets if design validation of the initial build was not able to happen as part of the tickets above.

- [ ] Application sign up: Design review/validation #155
- [ ] Application sign in: Design review/validation #156
