### ISSUE TITLE
[Epic] Plan for week of 10/13 - 10/19

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#249]
### PM (Leah)

**Leah will add tickets later.**

### Design (Melissa)

**Still on LIHEAP**

### Content (Allyce)

- [x] Review current quick submit and end to end flows #247
- [x] Continue onboarding guide #248

**Allyce will add tickets after team sync tomorrow.**

### Brian (Design)

- [ ] Review current quick submit and end to end flows #247
- [ ] Onboarding to the project **(Needs ticket)**

### Frontend (Mike)

- [ ] Document Windows installation directions for NJ DHS team #207

**Mike to add additional tickets when he's back.**

### Backend (Ron)

**Ron is out most of this week**

- [ ] [BE] Create endpoint for resetting a password after a user confirms their hint question #189
- [x] Bring on more engineers to the project **(Needs ticket)**
- [ ] Demo of OneTrac system **(Needs ticket)**
