### ISSUE TITLE
quick submit - an epic of epics

### ISSUE THREAD

**Issue by leahbannon2** [newjersey/dhs-oneapp#262]
"Quick submit," also know as "the 8%" by NJ, is the minimum required questions to start a SNAP application.

Note: This is a "soft MVP," in that we do not intend to launch to production, because drastically increasing the number of "quick submit" applications could have serious negative impacts on workload for caseworkers (they'll ultimately need to collect all the information from applicants) and applicants ("quick submit" is a faster way to start an application, but increases the time to receiving benefits)

### Why did we choose this MVP? 
- Policy: A quick submit experience is required by regulation (name, address, signature)
- Timing: Give design a chance to catch up to engineering
- Testing: Engineering can start QA and UAT, ensuring the data gets from our form through the system successfully (this takes up to an entire month for the mainframe system, FAMIS)
- Agile: Be more agile, help us find extra details/issues we might be missing in an end-to-end experience

What changes does this require to the questions?
- [ ] Work with NJ to define minimum "quick submit" questions required to initiate an application (including supporting folks experiencing homeless)
- [ ] Audit all content and design on staging for NJ comments, using our design principles heuristic, and QA
- [ ] Resolve Allyce's list of questions internally and then with NJ
- [ ] Quick submit IA
- [ ] Spanish translation (if NJ can translate just quick submit and doesn't require everything translated at once)
- [ ] Design and build additional pages required for quick submit end-to-end experience
  - [ ] checking the status of the application
  - [ ] submitting signatures (how does someone get from finishing the form to submitting required signatures, which is likely required for initiating a claim)
  - [ ] build pre-submit review page (already designed)
- [ ] Testing: unit tests, e2e tests, QA, UAT, accessibility, SEO
