### ISSUE TITLE
[Epic] Plan for week of 10/20 - 10/26

### ISSUE THREAD

**Issue by leahbannon2** [newjersey/dhs-oneapp#263]
### Leah (PM)
- [x] Continue onboarding guide #248
- Strategy meetings
- Onboarding
- OneTrac meeting
- Design planning/support

### Melissa (Design)

Rejoining sooooon!

### Allyce (Design and content)

- [ ] Get answers to open questions from NJ stakeholders #250
- [ ] [FE] Review homepage, login screens, style guide with Melissa #120
- [ ] [FE] Application sign up: Design review/validation #155
- [ ] IA for quick submit #261
- [ ] write issue for build pre-submit review page (already designed)

### Mike (Frontend)

- [ ] Document Windows installation directions for NJ DHS team and get them up and running #207
- [x] [FE] Form builder updates and related components for Basic Information section #176
- [ ] FE: Build out form component unit tests #246
- [x] Onboard Ben #269
- [ ] build pre-submit review page (already designed) (Allyce to write issue)

### Ron (Backend)

- [ ] Document Windows installation directions for NJ DHS team and get them up and running #207
- [ ] Onboard Maya #270
- [x] [BE] Create endpoint for resetting a password after a user confirms their hint question #189
- [x] Standard error messages on the front-end #186
- [x] [BE] Set up ability to send emails from GraphQL server #271
- OneTrac demo
