### ISSUE TITLE
Review designs for Quick Submit

### ISSUE THREAD

**Issue by allyceh** [newjersey/dhs-oneapp#275]
## Background

Allyce and Brian are new to the project and are picking up where design left off a month ago. There is [client feedback](https://dhs.invisionapp.com/share/NDYOY3WXCUR#/screens/426634090) for design to incorporate that currently lives in the InVision prototype, and we are learning more about quick submit from Alecia, notably, who will use it and reasons for using it. With Brian's knowledge about SNAP and the latest in the policy space, we also have the opportunity to improve the designs to better serve SNAP applicants. 

Overall, design can continue to strengthen the quick submit experience prior to delivering the MVP to NJ, and we need to assess the current quick submit experience before we create additional screens. 

## Tasks

- [ ] Determine how we can incorporate client feedback from a month ago
- [ ] Conduct a language review of quick submit
  - Are we using plain language? Is there anywhere in the app that language can provide greater transparency to the user?
- [ ] Does quick submit align with the design principles in CFA's [blueprint for a human-centered safety net](https://www.codeforamerica.org/safetynetblueprint/)?
- [ ] Are there ways that we can improve the UX of the experience?
  - UI patterns used
  - IA used
  - Flow of screens
- [ ] Does language and design align with accessibility best practices?

**Comment by bestes-usds** [comment]
Mural board of other States' quick submit flows: https://app.mural.co/t/ccs9461/m/ccs9461/1603468759519/65888f67070e3c448c362877effed13aef495e34

**Comment by allyceh** [comment]
@bestes-usds Would you be interested in tackling item 4, the audit against CFA's blueprint for a social safety net? I updated this ticket to include the 3 principles that I think pertain to content/design in the application, but we could select others or go beyond the CFA blueprint. Do you think there are other important principals to follow for SNAP applications?

We could start by auditing against the 3 principals. I'm not thinking anything super extensive that would take multiple days; rather, a quick gut check where we can identify some places in quick submit where we can better align with CFA's research findings and recommendations. 

When you click on the principle, scroll down and select "client", then expand the items in the "how to do it" section. CFA provides some guidelines to keep in mind, and that is what I am thinking we audit against. The goal of this audit would be to see if we're following those guidelines and identify areas for improvement. 

**Ideas on how to document audit findings**
- Create individual tickets in Github for each recommended improvement, tag them as design, assign yourself, @melissajschaff, and I and we can triage them later?
- Document findings in one github ticket called "audit findings"
- Spreadsheet?

**Comment by bestes-usds** [comment]
@allyceh I can tackle this. It might lean towards creating individual tickets, but don't have a strong preference. Will need to think if there are any other principles I might add, but the CfA ones are a great starting place.

**Comment by allyceh** [comment]
@bestes-usds I am revisiting [SNAP best practices](https://fns-prod.azureedge.net/sites/default/files/snap/Best-Practices-for-Online-SNAP-Applications.pdf) as I look at content. There are some other good principles in here. 

- Tell clients how information will be used
