### ISSUE TITLE
plan for week of 11/17

### ISSUE THREAD

**Issue by leahbannon2** [newjersey/dhs-oneapp#381]
###  Leah (PM)
- [ ] Create Service Blueprint/Customer Journey Map #294
- [ ] Work with Julie, Eddie to figure strategy with DHS NJ stakeholders/leadership

### Amal (PM)
- [ ] Create Service Blueprint/Customer Journey Map #294
- [ ] Work with Leah to set team priorities

### Allyce (Design and content)
- [ ] Review designs for Quick Submit #275 
- [ ] IA for quick submit #261
- [ ] Create user flows that reflect our current prototype and understand how eligibility impacts the prototype #253
- [ ] [FE] Review homepage, login screens, questions flow, and other screens in staging #120

### Brian (Design and Policy)
- [ ] Help with: [FE] Review homepage, login screens, questions flow, and other screens in staging #120
- [ ] Draft research plan for quick submit #291 

###  Mike (Frontend)
- [ ] Build out form component unit tests #246
- [ ]  Form builder updates and related components for Basic Information section #176
- [ ] Review homepage, login screens, questions flow, and other screens in staging #120

###  Ron (Backend)
- [ ] Onboard Maya #270
- [ ] Plan out the quick submit technical work #226
- more tickets to come based on #226

### Maya (Backend)

- [ ] [FE/BE] Write recommendations for QA process #295
- [ ] Create county and zipcode GraphQL queries and mutations#304
