### ISSUE TITLE
Basic Information Epic

### ISSUE THREAD

**Issue by amalabukar31** [newjersey/dhs-oneapp#384]
### Intro:

In an effort to modernize the benefits experience for Americans, USDS is beginning by transforming the digital user experience for residents of New Jersey.

### Product Requirement
- [ ] User should be to start an application from the homepage
- [ ] User should be able to translate the page in Spanish
- [ ] Homepage should be responsive on mobile, tablet, desktop

### Design Requirement (if any)
- [ ] 

### Engineering Requirement (if any)
- [ ] 

### QA Requirement (if any)
- [ ] review language with NJ
