### ISSUE TITLE
Plan for week of 11/24

### ISSUE THREAD

**Issue by amalabukar31** [newjersey/dhs-oneapp#431]
###  Leah (PM)
- [ ] Meeting with Julie, Eddie, and NJ to figure strategy with DHS NJ stakeholders/leadership (and then resulting planning)

### Amal (PM)
- [ ] Drafting user stories for quick submit #389 
- [ ] work on upcoming epics

### Allyce (Design and content)
- [ ] Review designs and content for Quick Submit #275 
- [ ] Drafting user stories for quick submit #389 
- sync with Mike on accessibility needs

### Brian (Design and Policy)
- [ ] Draft research plan for quick submit #291 (need to sync with Melissa)
- [ ] Drafting user stories for quick submit #389 
- [ ] Drafting copy and content review for quick submit

### Melissa (Design)
- [ ] UX and accessibility review of quick submit designs
- sync with Brian on research plan
- sync with Mike on accessibility needs
- [ ] review of staging #120

###  Mike (Frontend)
- [ ] Build out form component unit tests #246
- [ ] Form builder updates and related components for Basic Information section #176 (waiting on counties #304)
- [ ] Review homepage, login screens, questions flow, and other screens in staging #120
- hackathon
- Vue components on mobile issues (needs issue)
- presubmit page

###  Ron (pivoting to Frontend)
- GraphQL integrations on frontend
- VueJS components
(will sync with Mike about this)
- CMS and healthcare.gov meetings

### Maya (Backend)

- [ ] [FE/BE] Write recommendations for QA process #295 (meeting with Allyce on this)
- [ ] Create county and zipcode GraphQL queries and mutations #304
