### ISSUE TITLE
Plan for 12/1

### ISSUE THREAD

**Issue by amalabukar31** [newjersey/dhs-oneapp#453]
###  Leah (PM)
- [ ] prep for NJ contractor meeting 
- [ ] review user stories for quick submit

### Amal (PM)
- [ ] documentation, project roadmap
- [ ] work on upcoming epics-ongoing

### Allyce (Design and content)
- [ ] Review designs and content for Quick Submit #275 
- [ ] prep for team strategy meeting
-[ ] Design the post-quick submit flow#251

### Brian (Design and Policy)
- [ ] Draft research plan for quick submit #291 (update doc based on Melissa sync)
- [ ] Drafting copy and content review for quick submit

### Melissa (Design)-out until Monday
- [ ] UX and accessibility review of quick submit designs
- sync with Brian on research plan
- sync with Mike on accessibility needs
- [ ] review of staging #120

###  Mike (Frontend)
- [ ] Build out form component unit tests #246
- [ ] Form builder updates and related components for Basic Information section #176 -ready for review
- [ ] Form Builder authentication #444 
- [ ] Get form-builder ready for deployment to cloud.gov #445 
- [ ] Review application page (pre-submit)#446
-[ ] Vue components on mobile issues (needs issue)

###  Ron (Frontend)
- GraphQL integrations on frontend (will capture in tickets)
- [ ] Deploy form-builder to Cloud.gov #438 

### Maya (Backend)
- [ ] GraphQL PRS 
- [ ]  continue GraphQL Query and Mutation tickets
