### ISSUE TITLE
Plan for 12/7 - 12/11

### ISSUE THREAD

**Issue by allyceh** [newjersey/dhs-oneapp#467]
### Amal (PM)
- [ ] 

### Allyce (Design and content)
- [ ] Review copy for confirmation page #[458](https://app.zenhub.com/workspaces/oneapp-project-5f2aa7b989cf78000f31bdb5/issues/newjersey/dhs-oneapp/458)
- [ ] Start discovery repo and create brainstorming document
- [ ] Draft list of documentation needs prior to transition (add to Ron's doc)
- [ ] Start list of initial questions for states (like CO) once we get in touch

### Brian (Design and Policy)
- [ ] Draft research plan for quick submit #291 (update doc based on Melissa sync)
- [ ] Drafting copy and content review for quick submit (confirmation page)

### Melissa (Design)
- [ ] UX and accessibility review of quick submit designs
- sync with Brian on research plan
- sync with Mike on accessibility needs
- [ ] review of staging #120

###  Mike (Frontend)
- [ ] Build out form component unit tests #246
- [ ] Form builder updates and related components for Basic Information section #176 -ready for review
- [ ] Form Builder authentication #444 
- [ ] Get form-builder ready for deployment to cloud.gov #445 
- [ ] Review application page (pre-submit)#446
-[ ] Vue components on mobile issues (needs issue)

###  Ron (Frontend/Backend)
- GraphQL integrations on frontend (will capture in tickets)
- [ ] Deploy form-builder to Cloud.gov #438 
- [ ] mapping form builder fields to graphql model (meeting with Mike to discuss) #439 
- [ ] help with Form Builder authentication #444 
- [ ] write integration tests for the data layer/backend

 ### Maya (Backend)
- [ ] GraphQL PRS 
- [ ]  continue GraphQL Query and Mutation tickets (mailing address validations)
