### ISSUE TITLE
[BE] Create audit of Oracle procedures

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#55]
## Background

In the Oracle database, there are procedures that the frontend will need to call. We need to build out GraphQL nodes for all of those procedures.

In order to now what we are dealing with, Ron should conduct an audit of all the procedures in Oracle.

## Tasks

- [x] Create audit of Oracle procedures for NJ SNAP benefits app.
- [x] Add documentation of that audit to [this Github folder](https://github.com/usds/covid-19/tree/master/new-jersey/safety-net-benefits/one-app-datapoints).

## Acceptance criteria

- [x] Ron has completed and documented this audit and has a good enough sense of Oracle procedures to start moving forward with GraphQL work.

**Comment by ronaldheft-usds** [comment]
Documentation is done. Added to a different GitHub location. Instead, we are keeping the list with the development repository.

List of stored procedures is here: https://github.com/newjersey/dhs-oneapp/blob/main/development/Stored_Procedures.md

There are 151 stored procedures to migrate.

/cc @mikepif so this list can help inform your priorities. I am working on converting that initial set of stored procedures I called out in #121.
