### ISSUE TITLE
[PM] Figure out process for NJ team providing Spanish translation

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#58]
## Background

Spanish translation epic #21

We need to work with NJ to figure out how they expect to receive content for Spanish translation, how they will deliver the Spanish translation, and how long they need to provide us that translation.

## Tasks

- [ ] Figure out in what format NJ team wants to receive content.
- [ ] Figure out how long the NJ team needs to provide the Spanish translation.
- [ ] Figure out in what format the translation will be delivered to us.

**Comment by leahbannon2** [comment]
We discussed this with NJ. We believe an approach where translations are done on a regular basis (as sections are completed) is likely better. NJ is checking on the process required, since they're paying for an external contractor to complete this work.

**Comment by leahbannon2** [comment]
Mike will export the list of questions to an excel file once finalized. NJ will use a contractor to conduct the translation.

**Comment by Samara-Strauss** [comment]
- The NJ team is hiring a company to do the Spanish translation, so this process comes down to how the company plans on working with us.
- Otherwise, this is blocked until the questions for the app are finalized.
