### ISSUE TITLE
[FE] Implement Spanish translation: Section 0 — Account and application screens

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#62]
## Background

Spanish translation epic #21

When the Spanish translation is complete, Mike needs to implement it throughout the app.

**This ticket is blocked until the Spanish translation is complete.**

## Tasks

Implement Spanish translation for Section 0 — Account and application screens on the following pages:

- [ ] Account sign up
- [ ] Account sign in
- [ ] Forgot username
- [ ] Forgot password
- [ ] Check application status
- [ ] View application list
