### ISSUE TITLE
[Epic] Design: Section 1 — Basic Information

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#72]
## Background

There is still a significant amount of work that needs to happen on the Basic Information section. This epic will track tickets associated with that work.

## Tasks

- [ ] Review policy documentation from NJ team #73
- [ ] Make updates to the basic information section based on policy requirements and other NJ feedback #74
- [ ] Document validation rules & copy #75
- [ ] Document any conditional functionality #76
- [ ] Provide content for dropdowns #77
- [ ] Document mapping between old application and new application #78
- [ ] Content #128

**Comment by Samara-Strauss** [comment]
Marking this as blocked for the following reasons:

- Melissa is on the RI sprint for a few weeks.
- Completing the design details for the Basic Info section entirely depends on getting the questions approved, and that work is slowly making progress through Melissa's IA mapping. But the IA work is going to take some time, so the design work documented in this epic is otherwise on hold.
