### ISSUE TITLE
[Design] Review policy documentation from NJ team

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#73]
## Background

In the 8.19.20 regroup with the NJ team, the NJ team handed off some policy documentation to Melissa that will affect the design of the basic information section and the rest of the app. This includes some of the following:

- People need to be able to submit the application on any page.
- We need to ask certain required information on the first page of the basic info section — Name, address, email, program the applicant is interested in.

Melissa needs to review this documentation and see if there are other relevant policy requirements that she needs to incorporate into the design.

## Tasks

- [x] Add that documentation to Github
- [x] Link that documentation to this ticket
- [ ] Read/review the documentation
- [ ] Create a list of additional design requirements based on that documentation
- [ ] Add that list or requirements to this ticket

**Comment by Samara-Strauss** [comment]
Review this in 9.2.20 design meeting

**Comment by leahbannon2** [comment]
Allyce has taken the lead on this and created additional issues to resolve remaining questions.
