### ISSUE TITLE
[Design] Basic information: Make updates to this section based on policy requirements and other NJ feedback

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#74]
## Background

Melissa met with the NJ team on 8.19.20 and received some new policy guidance (#73) and design feedback. This ticket is for implementing the changes based on that feedback and the new policy guidance we have.

## Tasks

- [ ] Add ability to submit the app on every page of basic info section post-emergency/quick submit (and every page of application)
- [ ] Adjust order of required questions in basic info to put name/address/email/program interest first.
- [ ] Incorporate any other updates as required by the policy guidance provided.
- [ ] Update the order of the basic info section based on NJ's feedback.
