### ISSUE TITLE
[Design] Basic information: Document validation rules & copy

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#75]
## Background

We need validation rules and copy documented for the basic information section. This includes:

- What fields are required
- What happens if someone submits a form without filling out the required fields
- Any other field validation (if applicable) outside of "required" validation
- All validation copy/error messages

## Tasks

Provide the following in InVision:

- [ ] What fields are required
- [ ] What happens if someone submits a form without filling out the required fields
- [ ] Any other field validation (if applicable) outside of "required" validation
- [ ] All validation copy/error messages
