### ISSUE TITLE
[Design] Basic information: Create documentation around old/new questions

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#78]
## Background

Ron and Mike have requested the following documentation:

- Order of new questions and answers
- How the old application maps to the new application

For this ticket, Melissa will create this documentation for the basic information section only.

# Tasks

- [ ] Document order of all questions and answers for the new basic info section
- [ ] Document how the new app maps to the old app for the basic info section
- [ ] Add this document to Github
- [ ] Work with Samara to create necessary build tickets coming out of this
