### ISSUE TITLE
[Design] Section 0: Account and application screens — Document validation rules & copy

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#79]
## Background

We need validation rules and copy documented for Section 0: Account and application screens. This includes:

- What fields are required
- What happens if someone submits a form without filling out the required fields
- Any other field validation (if applicable) outside of "required" validation
- All validation copy/error messages

## Tasks

Provide the following in InVision:

- [ ] What fields are required
- [ ] What happens if someone submits a form without filling out the required fields
- [ ] Any other field validation (if applicable) outside of "required" validation
- [ ] All validation copy/error messages

**Comment by leahbannon2** [comment]
This issue is no longer relevant.
