### ISSUE TITLE
[Epic] Design: Section 6 — Resources

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#84]
## Background

This epic is intended to document the design needs for Section 6: Resources.

## Tasks

**Note**: Will create specific tickets for this epic later.

- [ ] Review existing designs with NJ team 
- [ ] Make updates to the income section based on NJ feedback 
- [ ] Document validation rules & copy 
- [ ] Document any conditional functionality 
- [ ] Provide content for dropdowns 
- [ ] Document mapping between old application and new application
