### ISSUE TITLE
[PM/Design] Verify existing sections/figure out what additional sections we need to design

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#85]
## Background

In the prototype, there are 6 sections of the app right now:

- Basic information
- Income
- Expenses
- Programs
- SNAP/WFNJ
- Resources

We should confirm these are indeed the first 6 sections of the app.

The prototype also shows that there are 8 sections. We need to figure out what the other two sections are. Is this something that we define, or is this something that NJ outlines for us based on the old application?

## Tasks

- [ ] Determine if the six sections listed above are indeed the first sections of the app.
- [ ] Determine what additional sections of the app we need. Is this taken from the old app and give to us from NJ? or do we determine this based on how we want to restructure things?
- [ ] Document findings in this ticket
