### ISSUE TITLE
Establish new OneApp success metrics for Google Analytics tracking

### ISSUE THREAD

**Issue by johnhashva** [newjersey/dhs-oneapp#89]
## Description

Designing and engineering a new OneApp that **is simpler and easier for users** is one of the project's chief goals.   To track our success, we have identified the following three success metrics in collaboration with NJ-DHS:

1. **Decrease OneApp abandonment rate**, as defined by the number of applications started, but not submitted.
2. **Increase average percent complete of the application**.  The more information applicants provide online, the less back-end administrative time/resource is required to process benefit eligibility.
3. **Average user rating** provided via online form/poll.

## Tasks

- [X] Work with NJ-DHS to pull OneApp usage data to establish the success metrics baselines (e.g. current abandonment rate)
- [ ] Finalize the success metrics baselines and goals. 
- [ ] Instrument the app via Google Analytics to track performance against the abandonment rate and percent complete success metrics.

### Additional Detail/Documentation

Project and Success Metrics Dashboard (PDF)
[https://app.zenhub.com/files/284097858/71461c40-bbed-47bb-9f12-09d1d17557e4/download](https://app.zenhub.com/files/284097858/71461c40-bbed-47bb-9f12-09d1d17557e4/download)
